config/routes.rb
Travel::Application.routes.draw do
  resources :uzers

  get "omniauth_callbacks/facebook"

  get "omniauth_callbacks/vkontakte"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  resources :leads
  resources :itineraries do
    resources :points
    member do
      get 'participate'
    end

    resources :comments, only: [:create, :update, :destroy]
  end

  root :to => 'itineraries#index'
  root :to => 'users#index'

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  acts_as_commentable
  attr_accessible :description, :name, :user_id
  has_many :points
  has_many :users, through: :user_itineraries
  has_many :user_itineraries
  belongs_to :owner,  foreign_key: :owner_id, class_name: 'User'
end

app/controllers/itineraries_controller.rb
class ItinerariesController < InheritedResources::Base
  load_and_authorize_resource
  has_scope :page, :default => 1

  def participate
    @participant = @itinerary.user_itineraries.new(user_id: current_user.id)
    if @participant.save
      flash[:success] = 'Success'
    else
      flash[:alert] = 'Error'
    end
    redirect_to itinerary_path(@itinerary)
  end

  def show
    @points = @itinerary.points
    @comment = Comment.new
    @hash = Gmaps4rails.build_markers(@points) do |point, marker|
      marker.lat point.latitude
      marker.lng point.longitude
      marker.infowindow point.description
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itenerary }
      format.json { render json: @hash }
    end
  end

  def index
    if params[:owned] && current_user.present?
      scope = current_user.itineraries
    else
      scope = Itinerary
    end
    @itineraries = scope.order('created_at desc').page(params[:page]).per(5)
    @hash = Gmaps4rails.build_markers(Itinerary.first.try(:points)) do |point, marker|
      marker.lat point.latitude
      marker.lng point.longitude
      marker.infowindow point.description
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hash }
      format.js
    end
  end

  def create
    @itinerary = Itinerary.new(params[:itinerary])
    @itinerary.owner_id = current_user.id
    respond_to do |format|
    if @itinerary.save
      @itinerary.user_itineraries.create(user_id: current_user.id)
      format.html { redirect_to @itinerary, notice:'itinerary was successfully created.' }
      format.json { render json: @itinerary, status: :created, location: @itinerary }
    end
  end
  # create вызывается много раз, работает не правильно
  #   create! { itineraries_path }
  # # POST /users
  # # POST /users.json
  #   @user = User.new(params[:user])
  #   respond_to do |format|
  #     if @user.save
  #       # Сказать UserMailer отослать приветственное письмо после сохранения
  #       UserMailer.welcome_email(@user).deliver

  #       format.html { redirect_to(@user, notice: 'User was successfully created.') }
  #       format.json { render json: @user, status: :created, location: @user }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #       avatar
  #     end
  #   end
  end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
  def can_view_self_itineraries?
    params[:owned].present? && current_user.present?
  end
end

app/views/itineraries/_comment_form.html.haml
= form_for @comment, url: itinerary_comments_path(@itinerary), method: :post do |f|
  = f.label :Заголовок
  = f.text_field :title, class: 'form-control'
  = f.label :Комментарий
  = f.text_area :comment, class: 'form-control', rows: '6'
  %br
  = f.submit class: 'btn btn-info', value: 'Оставить комментарий'

app/views/itineraries/_comments.html.haml
- itinerary.comments.each do |comment|
  %blockquote
    %p
      %b= comment.title
      %em
        (by 
        %b #{comment.user.email}
        , #{comment.created_at.to_s(:short)})

    %p= comment.comment
  

app/views/itineraries/_form.html.haml
= form_for @itinerary, :html => {:class => 'form-horizontal'} do |f|
  - if @itinerary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@itinerary.errors.count, "error")} prohibited this itinerary from being saved:"
      %ul
        - @itinerary.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10= f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10= f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary col-sm-4'

app/views/itineraries/_itineraries_list.html.haml
- itineraries.each do |itinerary|
  = link_to itinerary, class: 'list-group-item' do
    %h4.list-group-item-heading
      %strong= itinerary.name
    %p.list-group-item-text
      = itinerary.description
      %p
        %b Количество участников:
        = itinerary.users.size

app/views/itineraries/edit.html.haml
=render "shared/sign_reg_buttons"
%h1 Editing itinerary

= render 'form'

= link_to 'Show', @itinerary
\|
= link_to 'Back', itineraries_path

app/views/itineraries/index.html.haml
= content_for :navbar do
  = render 'shared/navbar'

/ = image_tag avatar_url(current_user)  - Неправильно работает
/ = link_to "Invite a friend", new_user_invitation_path, :class => 'btn btn-primary'

= content_for(:page_header) { can_view_self_itineraries? ? 'Мои маршруты' : 'Все маршруты' }
= content_for(:page_actions) { link_to 'Новый маршрут', new_itinerary_path, class: 'btn btn-primary' if can? :create, Itinerary }

= paginate @itineraries, :remote => true
.list-group
  = render 'itineraries_list', itineraries: @itineraries

= content_for :map do
  = render "shared/map"

= content_for :footer do
  =render 'shared/social'

app/views/itineraries/index.js.erb
$('.list-group').html("<%= j render  'itineraries_list',  itineraries: @itineraries %>");
$('ul.pagination').replaceWith('<%= escape_javascript(paginate @itineraries, remote: true)%>')

app/views/itineraries/new.html.haml
= content_for :navbar do
  = render 'shared/navbar'

= content_for(:page_header) { 'New itinerary' }

= render 'form'
= content_for :footer do
  =render 'shared/social'

app/views/itineraries/show.html.haml
= content_for :navbar do
  = render 'shared/navbar'

.row
  .col-lg-9
    %p.lead
      %b Название маршрута:
      = @itinerary.name
  .col-lg-3.text-right
    = link_to 'Вступить', participate_itinerary_path(@itinerary), class: 'btn btn-success' if can?(:participate, @itinerary)
    = link_to 'Удалить маршрут', itinerary_path(@itinerary), method: :delete, class: 'btn btn-success' if can?(:destroy, @itinerary)
= render "shared/points"
%br
%p.lead
  %b Описание:
  %blockquote= @itinerary.description

%p.lead
  %b Участники
  = "(#{@itinerary.users.size})"
  %ul
  - @itinerary.users.each do |user|
    %li= "#{user.fullname} (#{user.email})"

%p.lead
  %b Комментарии
  = "(#{@itinerary.comments.size})"
  = render 'comments', itinerary: @itinerary

.col-lg-6= render('comment_form', comment: @comment) if can? :create, Comment

= content_for :map do
  = render "shared/map"

= content_for :footer do
  = render "shared/social"