config/routes.rb
Travel::Application.routes.draw do
  resources :uzers

  get "omniauth_callbacks/facebook"

  get "omniauth_callbacks/vkontakte"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  resources :leads
  resources :itineraries do
    resources :points
    member do
      get 'participate'
    end

    resources :comments, only: [:create, :update, :destroy]
  end

  root :to => 'itineraries#index'
  root :to => 'users#index'

end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :name, :description, :latitude, :longitude
  belongs_to :itinerary
end

app/controllers/points_controller.rb
class PointsController < InheritedResources::Base
  load_and_authorize_resource

  belongs_to :itinerary
  def create
    @itinerary= Itinerary.find(params[:itinerary_id])
    @point = @itinerary.points.new(params[:point])
    respond_to do |format|
    if @point.save
      format.js { }
    end
  end

  def destroy
    @point = Point.find(params[:id])
    if @point.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/_point.html.erb
<br> 
<span class='point' id="<%=point.id%>" >

  <span class='label label-success label-90'>
    <botton class = "pointbot" lat="<%= point.latitude %>", lng = "<%= point.longitude %>">  <%= point.name%> </botton>
    <% if can? :destroy,  @itinerary %>
      <%=link_to '&#10006;'.html_safe, itinerary_point_path(itinerary, point), remote: true, method: :delete, class: 'red-cross' %>
    <% end %>
  </span>
  <br>
  <div class="description" style="display: none">  
    &ensp; <%= point.description%>
    <br> 
  &nbsp;
  </div>
  <br>
</span>

app/views/points/create.js.erb
$('#points-wrap').append("<%= j render 'point', point: @point, itinerary: @itinerary %>");

app/views/points/destroy.js.erb
var destroy = function () {
	$('#<%=@point.id%>').fadeOut();
}
destroy()

$( destroy ).ready(function() {
  $("#map-canvas").load("#map-canvas");
})

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<%= render "shared/sign_reg_buttons" %>
</div>

<% for user in @users %>
  <tr>
    <td><%= image_tag avatar_url(user) %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>

<body>
    <header>
    </header>
      <div class="heading">
          <h1>Места</h1>
      </div>
        <div class="heading"></div>
        <h3 class='clearfix'>Ваши места</h3>
        <div class="row">

  <%= render "shared/map" %>

<%= render 'shared/social' %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>
<% title "User" %>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Avatar Url:</strong>
  <%= @user.avatar_url %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>