config/routes.rb
Travel::Application.routes.draw do
  resources :uzers

  get "omniauth_callbacks/facebook"

  get "omniauth_callbacks/vkontakte"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  resources :leads
  resources :itineraries do
    resources :points
    member do
      get 'participate'
    end

    resources :comments, only: [:create, :update, :destroy]
  end

  root :to => 'itineraries#index'
  root :to => 'users#index'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :email, :name, :source
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  # GET /leads
  # GET /leads.json

   def index
    @leads = Lead.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end


  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(:email => params[:email])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to :action => :index}
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.number_field :source %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<!doctype html>
<html >
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic,cyrillic-ext" type="text/css" rel="stylesheet">
    <!--[if lt IE 9]><link href="https://new.landingi.com/bootstrap/css/ie8-grid.css?v=8.9.7" type="text/css" rel="stylesheet">
    <link href="https://new.landingi.com/uploads/7176542ae17000174108/landings/eqeedcfjN3kcTRz96ic1/styles/confirm_ie8.css?page=success" type="text/css" rel="stylesheet"><![endif]-->
    <link href="https://new.landingi.com/bootstrap/css/landend.bootstrap.min.css?v=8.9.8" type="text/css" rel="stylesheet">
    <link href="https://new.landingi.com/uploads/7176542ae17000174108/landings/eqeedcfjN3kcTRz96ic1/styles/confirm.css?page=success" type="text/css" rel="stylesheet">
  </head>
  <body id="wTb8R8gfl41xKhNxCydoeRTC5UwQLaw8">
    <div id="ZuSWZFVafzrX1Cq3KPiTcCJkgLgaovaO" class="widget widget-section">
      <div class="row">
        <div class="container">
          <div id="aVcon6UfgEmhJ8mVnx2R3CKyNgAaGcTq" class="col-12">
            <div id="X6aUoNBek6LPnWSfMIM2EU0E8xyMyZAT" class="widget widget-text">
              <p>Спасибо!</p>
            </div>
            <div id="ITaZMLwsuMvHSTTrGmreeFozOG2wrCdP" class="widget widget-text">
              <p>Мы обязательно сообщим вам, как только сервис заработает</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/bootstrap/js/landend.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/bootstrap/js/bootbox.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/libs/landingi/validator.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/landing.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/branding.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/libs/jquery/jquery-placeholder.js"></script>
    <script type="text/javascript">$(function() {
        $("input, textarea").placeholder();
      });</script>
    
   <%= render :partial => "shared/yandex" %>
  </body>
</html>

app/views/leads/new.html.erb
<!doctype html><html >
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic,cyrillic-ext" type="text/css" rel="stylesheet">
    <!--[if lt IE 9]><link href="https://new.landingi.com/bootstrap/css/ie8-grid.css?v=8.9.7" type="text/css" rel="stylesheet">
    <link href="https://new.landingi.com/uploads/7176542ae17000174108/landings/eqeedcfjN3kcTRz96ic1/styles/style_ie8.css" type="text/css" rel="stylesheet"><![endif]-->
    <link href="stylesheets/landend.bootstrap.min.css?v=8.9.8" type="text/css" rel="stylesheet">
    <link href="stylesheets/style.css" type="text/css" rel="stylesheet">
  </head>
  <body id="z77RxvIKTq75FN2GbpxHhO43v1lN5M79">
    <div id="ry4ApEskHmd4cTycm7uvWcrCFV73dcZ3" class="widget widget-section">
      <div class="row">
        <div class="container">
          <div id="POPAABVTtwVlgWntxz1rnzcXhJ9Uu5oW" class="col-12">
            <div id="SDw8DmcTtJ4lpgFxskHKdBGPUUH68oOJ" class="widget widget-text">
              <p>Сделать путешествие самому - быстро, удобно и экономно</p>
            </div>
            <div id="aWGLhwI9g3f91F9F00xBRN8DbL7p1uo0" class="widget widget-text" style="text-align: center">
              <br/><br/><br/><br/><br/>
              <table border="0" style="width: 100%; height: 100%;margin: 0 auto">
                <tr>
                  <td style="text-align: left">
                    <span style="font-size: 36px">Создавай</span>
                    <br/>
                    маршруты
                    <br/>
                    команды
                  </td>
                  <td style="text-align: left">
                    <span style="font-size: 36px">Делись</span>
                    <br/>
                    впечатлениями
                    <br/>
                    опытом                  
                  </td>
                  <td style="text-align: left">
                    <span style="font-size: 36px">Путешествуй</span>
                    <br/>
                    просто
                    <br/>
                    экономно
                  </td>
                  
                </tr>
              </table>
            </div>
            <form id="h1Phv2RAtTxNnX3bXnDF0k9ufqfXme4O" class="widget widget-form" action="<%=leads_path%>" method="post" novalidate>
              <div id="OHfQLDvhBgxwLkNouKMzeFntvHyeu1Pv" class="widget widget-container">
                <br/><br/><br/><br/><br/><br/><br/>
                <label id="ksKIABoWHBSQTIZyp3TkOT4TxdgKxZfD" class="widget widget-text widget-label"></label>
                <input class="widget widget-input-text" id="wtqhIHzG57bQziVfFsclpKLVBOUGL05B" type="email" subtype="email" placeholder="Почта" parentId="h1Phv2RAtTxNnX3bXnDF0k9ufqfXme4O" name="email"  value="">
              </div>
              <div id="UJtE7grlS5bsiHRIzKgLUeoiiPyecsbG" class="widget widget-container input-button-container">
                <button class="widget widget-input-button" type="submit" id="UdKs6SA87sI3qcnC5sFDIHoPfAJmGgSG" parentId="h1Phv2RAtTxNnX3bXnDF0k9ufqfXme4O">Узнать первым</button>
              </div>
              <input type="hidden" name="_uid" value="h1Phv2RAtTxNnX3bXnDF0k9ufqfXme4O">
            </form>
          </div>
        </div>
      </div>
    </div>
    <div id="RAT9089SiPnQR24pkskZyreTa4wJvtJb" class="widget widget-section">
      <div class="row">
        <div class="container">
          <div id="PyhRs3AzsZ4VpsQbii7TOT0FVsl7T5i1" class="col-12">
            <img id="rHIHltcH74aSMyelewlCZxgDl1RCGRNM"  width="8" height="11"  class="widget widget-image" src="http://custream.com/uploads/bd7f19e4589390695628/pictures/894b7aa2d3d37c1dfee1f959313f84d0.png"  alt=""/>
            <div id="hd4byTfC9cHSwJWJ6ueWWz2I0NbGuAcT" class="widget widget-text">
              <p>Маршруты</p>
            </div>
            <div id="Kyusfqt5laa1aunXZQxDxWuP7NkEoUUm" class="widget widget-text">
              <p>
                Создавай маршруты на карте в 3 клика<br/>
                Собери все свои маршруты в одном месте
              </p>
            </div><div id="n5hv8cfsXiMLbKaeVcaVhlcAWynLWVKk" class="widget widget-text">
              <p>Команда</p>
            </div>
            <div id="pJJ9ymot3bSUpU1Paz1eTZq4Z1MB96BT" class="widget widget-text">
              <p>
                Набирай команду для путешествий<br/>
                Присоединяйся к опытным путешественникам
              </p>
            </div>
            <div id="S2irqL5tMmEXylPGBukycKapcEUiT14M" class="widget widget-text">
              <p>Отчеты</p>
            </div>
            <div id="A8EeV1MF9glk8AySVlu1QbCqAbTT8q8a" class="widget widget-text">
              <p>
                Делись впечатлениями от поездок<br/>
                Испольуй опыт живых путешествий
              </p>
            </div>
            
            <img id="Iykk3OLSvmpOPOpFlwkg6F5Pw2GbFi7Q"  width="8" height="10"  class="widget widget-image" src="http://custream.com/uploads/bd7f19e4589390695628/pictures/1bb00ba0f84cd3c752be068e0c3d10fe.png"  alt=""/>
            <img id="KMF7ASDx7cDiSCRAatEINszeAHCT2N4T"  width="8" height="10"  class="widget widget-image" src="http://custream.com/uploads/bd7f19e4589390695628/pictures/19a2ce1851f9f62731279d59fc7f4762.png"  alt=""/>
            
          </div>
        </div>
      </div>
    </div>
    <div align="center">
      <div style='width: 2000px;'>
        <div id="map" style='width: 1000px; height: 600px;'>
        </div>
      </div>
    </div>
  
 
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/bootstrap/js/landend.bootstrap.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/bootstrap/js/bootbox.min.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/libs/landingi/validator.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/landing.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/branding.js"></script>
    <script type="text/javascript" src="https://new.landingi.com/js/libs/jquery/jquery-placeholder.js"></script>
    <script type="text/javascript">$(function() {
        $("input, textarea").placeholder();
      });</script>
   <%= render :partial => "shared/yandex" %>
  </body>
</html>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @lead.email %>
</p>

<p>
  <b>Source:</b>
  <%= @lead.source %>
</p>

<p>
  <b>Name:</b>
  <%= @lead.name %>
</p>


<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>