config/routes.rb
Travel::Application.routes.draw do
  resources :uzers

  get "omniauth_callbacks/facebook"

  get "omniauth_callbacks/vkontakte"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  resources :leads
  resources :itineraries do
    resources :points
    member do
      get 'participate'
    end

    resources :comments, only: [:create, :update, :destroy]
  end

  root :to => 'itineraries#index'
  root :to => 'users#index'

end

app/helpers/uzers_helper.rb
module UzersHelper
end

app/views/uzers/_form.html.haml
= form_for @uzer do |f|
  - if @uzer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@uzer.errors.count, "error")} prohibited this uzer from being saved:"
      %ul
        - @uzer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :login
    = f.text_field :login
  .actions
    = f.submit 'Save'

app/views/uzers/edit.html.haml
%h1 Editing uzer

= render 'form'

= link_to 'Show', @uzer
\|
= link_to 'Back', uzers_path

app/views/uzers/index.html.haml
%h1 Listing uzers

%table
  %tr
    %th Имя
    %th Email
    %th Логин
    %th
    %th
    %th

  - @uzers.each do |uzer|
    %tr
      %td= uzer.name
      %td= uzer.email
      %td= uzer.login
      %td= link_to 'Show', uzer
      %td= link_to 'Edit', edit_uzer_path(uzer)
      %td= link_to 'Destroy', uzer, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

= link_to 'New Uzer', new_uzer_path

app/views/uzers/new.html.haml
%h1 New uzer

= render 'form'

= link_to 'Back', uzers_path

app/views/uzers/show.html.haml
%p#notice= notice

%p
  %b Имя:
  = @uzer.name
%p
  %b Email:
  = @uzer.email
%p
  %b Логин:
  = @uzer.login

= link_to 'Edit', edit_uzer_path(@uzer)
\|
= link_to 'Back', uzers_path